### ISSUE TITLE
ImportError: cannot import name 'is_linux'

### ISSUE THREAD

**Issue by BruceZhang1993** [cosven/feeluown-mpris2-plugin#1]
加载插件时的报错，去FeelUOwn dev分支似乎没找到这个is_linux函数
`[ERROR] [plugin.py line:40] : detect a bad plugin feeluown-mpris2-plugin
Traceback (most recent call last):
  File "/opt/feeluown-dev-git/feeluown/plugin.py", line 34, in scan
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/bruce/.FeelUOwn/plugins/feeluown-mpris2-plugin/__init__.py", line 3, in <module>
    from feeluown.utils import is_linux
ImportError: cannot import name 'is_linux'`

**Comment by BruceZhang1993** [comment]
https://github.com/cosven/FeelUOwn/pull/153   This should be enough,,
